[build]
  command = "pip install -r requirements.txt"
  publish = "static"  # Using static folder as it already exists in the Flask project

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app_handler"
  status = 200 